# railway.toml
[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "./bin/app"
restartPolicyType = "on_failure"

[[ports]]
port = "8080"
protocol = "http"

[variables]
GO_ENV = "production"
