# railway.toml
[build]
builder = "nixpacks"
buildCommand = "go build -o main cmd/server/main.go"

[deploy]
startCommand = "./main"
restartPolicyType = "on_failure"

[[ports]]
port = "8080"
protocol = "http"

[variables]
GO_ENV = "production"
